export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';

export const EDITAR_CONTA_SUCCESS = 'EDITAR_CONTA_SUCCESS';
export const EDITAR_CONTA_REQUEST = 'EDITAR_CONTA_REQUEST';
export const EDITAR_CONTA_FAILURE = 'EDITAR_CONTA_FAILURE';
